services:
    db:
        image: postgres:18.1-alpine3.23
        restart: always
        volumes:
            - ./data/db:/var/lib/postgres/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    web:
        image: nuwa:latest
        command: ["uv", "run", "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
        restart: always
        volumes:
            - ./config/uwsgi:/code/config/uwsgi
            - uwsgi_socket:/run/uwsgi
        env_file:
            - .env
        environment:
            - DJANGO_SETTINGS_MODULE=nuwa.settings.local
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        depends_on:
            - db
    nginx:
        image: nuwa-nginx:latest
        restart: always
        volumes:
            - uwsgi_socket:/run/uwsgi:ro
        ports:
            - "8000:8000"
            - "5173:5173"
        depends_on:
            - web
volumes:
    uwsgi_socket: