services:
    db:
        image: postgres:18.1-alpine3.23
        restart: no
        volumes:
            - ./data/db:/var/lib/postgres/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    rabbitmq:
        image: rabbitmq:4.2.3-management
        restart: no
        ports:
            - "15672:15672"
    web:
        image: nuwa:latest
        command: ["uv", "run", "--no-sync", "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
        restart: no
        volumes:
            - ./config/uwsgi:/code/config/uwsgi
            - uwsgi_socket:/run/uwsgi
        env_file:
            - .env
        environment:
            - ROLE=web
            - DJANGO_SETTINGS_MODULE=nuwa.settings.local
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        depends_on:
            - db
            - rabbitmq
    celery_worker:
        image: nuwa:latest
        command: ["uv", "run", "--no-sync", "celery", "-A", "nuwa", "worker", "-l", "info"]
        restart: always
        env_file:
            - .env
        environment:
            - ROLE=celery
            - DJANGO_SETTINGS_MODULE=nuwa.settings.prod
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
        depends_on:
            - db
            - rabbitmq
    celery_beat:
        image: nuwa:latest
        command: ["uv", "run", "--no-sync", "celery", "-A", "nuwa", "beat", "-l", "info"]
        restart: always
        env_file:
            - .env
        environment:
            - ROLE=celery
            - DJANGO_SETTINGS_MODULE=nuwa.settings.prod
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
        depends_on:
            - db
            - rabbitmq
    nginx:
        image: nuwa-nginx:latest
        restart: no
        volumes:
            - uwsgi_socket:/run/uwsgi:ro
        ports:
            - "8000:8000"
            - "5173:5173"
        depends_on:
            - web
volumes:
    uwsgi_socket: