"""create scheduled task

Revision ID: 21d91c89ea0f
Revises: 6aaba91b01b6
Create Date: 2026-02-25 09:49:45.894530

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21d91c89ea0f"
down_revision: Union[str, Sequence[str], None] = "6aaba91b01b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduled_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("center_time", sa.Time(), nullable=False),
        sa.Column("delta_minutes", sa.Integer(), nullable=False),
        sa.Column("user_timezone", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.String(), nullable=True),
        sa.Column("use_time", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("edited_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "delta_minutes >= 0 AND delta_minutes <= 360", name="ck_delta_minutes"
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chat.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_scheduled_task_created_at_desc",
        "scheduled_task",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_scheduled_task_created_at_desc", table_name="scheduled_task")
    op.drop_table("scheduled_task")
    # ### end Alembic commands ###
