"""create chat

Revision ID: 6a3802c0775f
Revises: 76390f29f37e
Create Date: 2026-02-25 09:47:55.408061

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a3802c0775f"
down_revision: Union[str, Sequence[str], None] = "76390f29f37e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("character_name", sa.String(length=50), nullable=False),
        sa.Column("system_prompt", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_hidden_prompt", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_message_text", sa.String(), nullable=True),
        sa.Column("last_message_datetime", sa.DateTime(), nullable=False),
        sa.Column("structure", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("edited_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["character.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_chat_last_msg_dt_desc",
        "chat",
        [sa.literal_column("last_message_datetime DESC")],
        unique=False,
    )
    op.create_index(
        "ix_chat_owner_last_msg_dt_desc",
        "chat",
        ["owner_id", sa.literal_column("last_message_datetime DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chat_owner_last_msg_dt_desc", table_name="chat")
    op.drop_index("ix_chat_last_msg_dt_desc", table_name="chat")
    op.drop_table("chat")
    # ### end Alembic commands ###
