"""create message

Revision ID: 6aaba91b01b6
Revises: 6a3802c0775f
Create Date: 2026-02-25 09:48:33.520829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aaba91b01b6'
down_revision: Union[str, Sequence[str], None] = '6a3802c0775f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=9), nullable=False),
    sa.Column('media_type', sa.String(length=5), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('media', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('conducted', sa.DateTime(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_chat_conducted_desc', 'message', ['chat_id', sa.literal_column('conducted DESC')], unique=False)
    op.create_index('ix_message_owner_chat_conducted_desc', 'message', ['owner_id', 'chat_id', sa.literal_column('conducted DESC')], unique=False)
    op.add_column('chat', sa.Column('last_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat', 'message', ['last_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_column('chat', 'last_message_id')
    op.drop_index('ix_message_owner_chat_conducted_desc', table_name='message')
    op.drop_index('ix_message_chat_conducted_desc', table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
