# Generated by Django 6.0.1 on 2026-01-15 11:42

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 1, 15, 11, 42, 15, 508328, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="character",
            name="edited_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
