# Generated by Django 6.0.1 on 2026-01-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_character_created_at_character_edited_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="is_hidden_prompt",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
