# Generated by Django 6.0.1 on 2026-01-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_character_is_hidden_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
