# Generated by Django 6.0.1 on 2026-01-17 09:43

import chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_character_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_name", models.CharField(max_length=50)),
                ("system_prompt", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("is_hidden_prompt", models.BooleanField()),
                ("is_active", models.BooleanField(default=True)),
                ("last_message_text", models.TextField()),
                ("last_message_datetime", models.DateTimeField(blank=True, null=True)),
                ("structure", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="chat.character",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "user"), ("assistant", "assistant")],
                        max_length=9,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("text", "text"),
                            ("image", "image"),
                            ("video", "video"),
                        ],
                        max_length=5,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "media_path",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=chat.models.chat_media_upload_path,
                    ),
                ),
                ("conducted", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chat",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-conducted"],
            },
        ),
        migrations.AddField(
            model_name="chat",
            name="last_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chat.message",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat", "-conducted"], name="chat_messag_chat_id_7436ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["-last_message_datetime"], name="chat_chat_last_me_ae2c2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["owner", "-last_message_datetime"],
                name="chat_chat_owner_i_2799a4_idx",
            ),
        ),
    ]
