# Generated by Django 6.0.1 on 2026-01-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_chat_message_chat_last_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="history",
            field=models.JSONField(default=list),
        ),
    ]
