# Generated by Django 6.0.1 on 2026-01-19 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_message_chat_messag_owner_i_44aa59_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="message",
            name="chat_messag_owner_i_44aa59_idx",
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["owner", "chat", "-conducted"],
                name="chat_messag_owner_i_66a165_idx",
            ),
        ),
    ]
