# Generated by Django 6.0.1 on 2026-01-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_remove_message_chat_messag_owner_i_44aa59_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="last_message_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
