# Generated by Django 6.0.1 on 2026-01-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_alter_chat_last_message_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="media_path",
            new_name="media",
        ),
    ]
