# Generated by Django 6.0.1 on 2026-01-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_rename_media_path_message_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
