# Generated by Django 6.0.1 on 2026-01-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_message_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="info",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
