# Generated by Django 6.0.1 on 2026-02-12 05:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_message_info"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduchedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("center_time", models.TimeField(help_text="In UTC")),
                (
                    "delta_minutes",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(360)]
                    ),
                ),
                ("user_timezone", models.IntegerField(help_text="In minutes")),
                ("prompt", models.TextField(blank=True, null=True)),
                ("use_time", models.BooleanField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduched_tasks",
                        to="chat.chat",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduched_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduchedMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduched_at", models.DateTimeField()),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduched_messages",
                        to="chat.chat",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduched_message",
                        to="chat.message",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduched_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.scheduchedtask",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduched_at"],
            },
        ),
        migrations.AddIndex(
            model_name="scheduchedtask",
            index=models.Index(
                fields=["-created_at"], name="chat_schedu_created_d8b5ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduchedmessage",
            index=models.Index(
                fields=["-scheduched_at"], name="chat_schedu_scheduc_b0e387_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scheduchedmessage",
            unique_together={("task", "scheduched_at")},
        ),
    ]
