# Generated by Django 6.0.1 on 2026-02-12 05:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_scheduchedtask_scheduchedmessage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("center_time", models.TimeField(help_text="In UTC")),
                (
                    "delta_minutes",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(360)]
                    ),
                ),
                ("user_timezone", models.IntegerField(help_text="In minutes")),
                ("prompt", models.TextField(blank=True, null=True)),
                ("use_time", models.BooleanField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="scheduchedmessage",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="scheduchedmessage",
            name="chat_schedu_scheduc_b0e387_idx",
        ),
        migrations.RemoveIndex(
            model_name="scheduchedtask",
            name="chat_schedu_created_d8b5ab_idx",
        ),
        migrations.AddField(
            model_name="scheduledmessage",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_messages",
                to="chat.chat",
            ),
        ),
        migrations.AddField(
            model_name="scheduledmessage",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_message",
                to="chat.message",
            ),
        ),
        migrations.AddField(
            model_name="scheduledmessage",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scheduledtask",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_tasks",
                to="chat.chat",
            ),
        ),
        migrations.AddField(
            model_name="scheduledtask",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scheduledmessage",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.scheduledtask",
            ),
        ),
        migrations.RemoveField(
            model_name="scheduchedmessage",
            name="chat",
        ),
        migrations.RemoveField(
            model_name="scheduchedmessage",
            name="message",
        ),
        migrations.RemoveField(
            model_name="scheduchedmessage",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="scheduchedmessage",
            name="task",
        ),
        migrations.RemoveField(
            model_name="scheduchedtask",
            name="chat",
        ),
        migrations.RemoveField(
            model_name="scheduchedtask",
            name="owner",
        ),
        migrations.AddIndex(
            model_name="scheduledtask",
            index=models.Index(
                fields=["-created_at"], name="chat_schedu_created_81cc5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledmessage",
            index=models.Index(
                fields=["-scheduled_at"], name="chat_schedu_schedul_172cb9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scheduledmessage",
            unique_together={("task", "scheduled_at")},
        ),
        migrations.DeleteModel(
            name="ScheduchedMessage",
        ),
        migrations.DeleteModel(
            name="ScheduchedTask",
        ),
    ]
