# Generated by Django 6.0.2 on 2026-02-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_scheduledmessage_scheduledtask_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledmessage",
            name="prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduledmessage",
            name="use_time",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
